FROM oven/bun:1

WORKDIR /app
COPY ./src/chat-front .
RUN bun install -f

RUN bun run build

USER bun

ENV PORT=80
ARG API_URL="app"
ENV API_URL=$API_URL

EXPOSE 80/tcp 443

# build

CMD bun run preview