services:
  frontend:
    container_name: frontend
    environment:
      API_URL: app
    build:
      context: ./
      dockerfile: Dockerfile-prod
    restart: unless-stopped
    volumes:
      - ./src/chat-front:/app/front/
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=chatDB
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile-dev-api
    container_name: nest-docker-postgres
    environment:
      PORT: 80
      DB_NAME: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    volumes:
      - ./src/chat-api:/app/api/

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - db
