FROM node:22-alpine
# FROM oven/bun:latest // error argon2 fix in 1.17

ARG PORT=80
ARG DB_PORT=5432
ARG DB_NAME='postgres'
ARG DB_HOST='db'
ARG DB_USERNAME='postgres'
ARG DB_PASSWORD='postgres'
ENV PORT=${PORT}
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_NAME=$DB_NAME

WORKDIR /app
COPY ./src/chat-api .
RUN npm install -f

EXPOSE 80/tcp 443

RUN npm run build

CMD npm run start 